"""Access to the KDP specification data.

Two files back this package, and the split is deliberate:

- ``kdp_specs.yaml``   hand-written scalars, each citing the help topic it came
                       from, checked by tests/test_specs_match_wiki.py
- ``trim_sizes.json``  the large tables, generated by tools/extract_kdp_specs.py
                       because transcribing them by hand is not safe
- ``book_defaults.yaml`` what "I don't know" resolves to, per book type, with
                       the reasoning for each choice

Nothing outside this package may hardcode a KDP number.

``book_defaults.yaml`` lives here rather than beside the skill because both
need it: the interview reads it to explain a choice, and the CLI reads it to
apply one. While it sat in the skill's references the CLI could not see it at
all, so `build` produced a 6x9 book with no contents while the interview was
telling the author it had chosen 5.5x8.5 with one.
"""
import functools
import json
import pathlib

import yaml

_HERE = pathlib.Path(__file__).resolve().parent


@functools.lru_cache(maxsize=1)
def constants():
    """The hand-written scalar specifications."""
    return yaml.safe_load((_HERE / "kdp_specs.yaml").read_text(encoding="utf-8"))


@functools.lru_cache(maxsize=1)
def book_defaults():
    """What "I don't know" resolves to, keyed by book type."""
    return yaml.safe_load(
        (_HERE / "book_defaults.yaml").read_text(encoding="utf-8"))


def book_types():
    return sorted(book_defaults())


@functools.lru_cache(maxsize=1)
def tables():
    """The generated trim-size, margin and bleed tables."""
    return json.loads((_HERE / "trim_sizes.json").read_text(encoding="utf-8"))


def margins():
    """Gutter and outside minimums, bracketed by page count."""
    return tables()["margins"]


def bleed_examples():
    """KDP's own worked trim -> bleed-page-size pairs, used as test fixtures."""
    return tables()["bleed_examples"]


def trim_sizes(binding="paperback", marketplace="com"):
    """Available trim sizes with their per-paper page-count limits."""
    return tables()["trim_sizes"][marketplace][binding]


def spine_factor(paper):
    """Inches of spine per page for a given paper stock."""
    return constants()["spine_factors_per_page"][paper]
