"""Extract KDP's specification tables from the wiki into machine-readable form.

The trim-size and margin tables are too large to transcribe by hand without
error, so they are parsed straight out of `wiki/topics/`. Scalars
(spine factors, bleed, thresholds) are hand-written in kdp_specs.yaml with a
citation, and `tests/test_specs_match_wiki.py` checks every one of them still
appears in the topic it claims to come from.

`kdp wiki build` runs this last and reports whether the tables changed.
"""
import json
import pathlib
import re

from . import TOPICS

OUT = pathlib.Path(__file__).resolve().parents[1] / "specs" / "trim_sizes.json"
TRIM_TOPIC = TOPICS / "set-trim-size-bleed-and-margins.md"

# "5.5" x 8.5" (13.97 x 21.59 cm)"  ->  (5.5, 8.5)
SIZE_RE = re.compile(r'^([\d.]+)"?\s*[xX]\s*([\d.]+)"')
# "24 - 828" / "75 – 550" (note the en dash KDP mixes in)
RANGE_RE = re.compile(r"^(\d+)\s*[-–]\s*(\d+)$")

PAPER_KEYS = ["white", "cream", "groundwood", "standard_color", "premium_color"]


def cells(row):
    return [c.strip().strip("*").strip() for c in row.strip().strip("|").split("|")]


def parse_trim_tables(text):
    """Walk the markdown, tracking the marketplace heading and binding/section."""
    marketplace, binding, out = None, None, {}
    for line in text.split("\n"):
        mp = re.search(r"\(kdp\.amazon\.([a-z.]+)\)", line)
        if mp:
            marketplace = mp.group(1)
            continue
        if not line.startswith("|"):
            continue
        c = cells(line)
        if not c:
            continue
        head = c[0].lower()
        if head in ("paperback", "hardcover"):
            binding = head
            continue
        if head in ("trim size", "---") or head.startswith("large trim"):
            continue
        m = SIZE_RE.match(c[0])
        # The bleed table further down the page also starts its rows with a
        # trim size, but carries two columns rather than six. Require the full
        # set of paper columns so those rows are not mistaken for trim specs.
        if not m or marketplace is None or binding is None or len(c) < 6:
            continue
        papers = {}
        for key, cell in zip(PAPER_KEYS, c[1:6]):
            r = RANGE_RE.match(cell)
            papers[key] = {"min": int(r.group(1)), "max": int(r.group(2))} if r else None
        out.setdefault(marketplace, {}).setdefault(binding, []).append({
            "width": float(m.group(1)),
            "height": float(m.group(2)),
            "papers": papers,
        })
    return out


def parse_margins(text):
    """Gutter and outside minimums, bracketed by page count."""
    rows = []
    for line in text.split("\n"):
        if not line.startswith("|"):
            continue
        c = cells(line)
        m = re.match(r"^(\d+)\s+to\s+(\d+)\s+pages$", c[0])
        if not m:
            continue

        def inches(cell):
            g = re.search(r"([\d.]+)\s*(?:\"|in\b)", cell)
            return float(g.group(1)) if g else None

        rows.append({
            "min_pages": int(m.group(1)),
            "max_pages": int(m.group(2)),
            "gutter": inches(c[1]),
            "outside_no_bleed": inches(c[2]),
            "outside_with_bleed": inches(c[3]),
        })
    return rows


def parse_bleed_examples(text):
    """KDP's worked examples of trim size -> page size with bleed.

    These are used as test fixtures: they pin the rule that bleed adds 0.125"
    to the width (outside edge only) but 0.25" to the height (top and bottom).
    """
    out = []
    for line in text.split("\n"):
        if not line.startswith("|"):
            continue
        c = cells(line)
        if len(c) != 2:
            continue
        a, b = SIZE_RE.match(c[0]), SIZE_RE.match(c[1])
        if not (a and b):
            continue
        out.append({
            "trim": [float(a.group(1)), float(a.group(2))],
            "with_bleed": [float(b.group(1)), float(b.group(2))],
        })
    return out


def extract():
    """Regenerate trim_sizes.json from the wiki. Returns True if it changed:
    KDP altered a trim, page-count or margin table, and the diff needs a look."""
    text = TRIM_TOPIC.read_text(encoding="utf-8")
    data = {
        "_source": "wiki/topics/set-trim-size-bleed-and-margins.md",
        "_note": "Generated by kdp/wiki/specs.py - do not edit by hand.",
        "trim_sizes": parse_trim_tables(text),
        "margins": parse_margins(text),
        "bleed_examples": parse_bleed_examples(text),
    }
    new = json.dumps(data, indent=1) + "\n"
    if OUT.exists() and OUT.read_text(encoding="utf-8") == new:
        return False
    OUT.write_text(new, encoding="utf-8")
    return True
